//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Movie_DataBase.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        // Строка подключения
        internal string ConnStr;

        // Запрос на включение роли приложения
        internal string RoleApp = "EXECUTE sys.sp_setapprole 'app', '123';";

        // Выбрана ли роль приложения
        internal bool IsRoleApp = false;

        // Стартовая форма при нажатии "Назад".
        // 0 - полноценная, 1 - модератор второго уровня
        internal int StartForm = 0;

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
